apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cxlmm0eul-python 
  janus-idp.io/tekton: cxlmm0eul-python
  backstage.io/kubernetes-id: cxlmm0eul-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cxlmm0eul-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  